version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "<-- RUNTIME EXECUTION -->"
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint

  pre_build:
    commands:
      - echo "PRE-Build stage"
      - python --version
      - python manage.py collectstatic --noinput
      - echo "pre build stage completed"

  build:
    commands:
      - echo "Build Stage"
      - echo "PyLint Started"
      - pylint sportsactive/**/*.py || true
      - echo "pre build stage completed - PyLint Completed!!"
      - echo "Django Test Cases Started"
      - python manage.py test
      - echo "Django Test Cases Completed!!"
      - echo "Build stage completed!"

artifacts:
  files:
    - '**/*'
