# Generated by Django 4.2.11 on 2024-04-07 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bookingapp", "0002_rename_end_time_bookedactivity_date_of_booking_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookedactivity",
            name="date_of_booking",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
